version: 2
updates:
  - package-ecosystem: "docker"
    # Files stored in repository root
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pip"
    # Files stored in repository root
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    # Files stored in repository root
    directory: "/"
    schedule:
      interval: "daily"
   - package-ecosystem: "github-actions"
    # Files stored in repository root
    directory: "/"
    schedule:
      interval: "daily"