<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:macro name="base" params="name parent *origin">

    <!-- ############################ -->
    <!-- ########## JOINTS ########## -->
    <!-- ############################ -->

    <!-- joint: base_footprint -> base -->
    <joint name="${parent}_to_${name}" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}"/>
      <child link="${name}"/>
    </joint>

    <!-- joint: base -> right_motor -->
    <joint name="${name}_to_right_motor" type="fixed">
      <origin xyz="${ 0.42/2 - 0.075 } ${-(base_motor_lenght/2 + base_motor_gap/2)} ${0.03-base_motor_diameter/2}" rpy="${-PI/2} 0 0"/>
      <parent link="${name}"/>
      <child link="right_motor"/>
    </joint>

    <!-- joint: base -> left_motor -->
    <joint name="${name}_to_left_motor" type="fixed">
      <origin xyz="${ 0.42/2 - 0.075 } ${(base_motor_lenght/2 + base_motor_gap/2)} ${0.03-base_motor_diameter/2}" rpy="${-PI/2} 0 0"/>
      <parent link="${name}"/>
      <child link="left_motor"/>
    </joint>

    <!-- joint: right_motor -> right_wheel -->
    <joint name="right_motor_to_right_wheel" type="continuous">
      <origin xyz="0 0 ${ -(base_wheel_lenght/2 + base_motor_lenght/2 + base_wheel_gap2base) }" rpy="0 0 0"/>
      <parent link="right_motor"/>
      <child link="right_wheel"/>
      <axis xyz="0 0 1"/>
    </joint>

    <!-- joint: left_motor -> left_wheel -->
    <joint name="left_motor_to_left_wheel" type="continuous">
      <origin xyz="0 0 ${(base_wheel_lenght/2 + base_motor_lenght/2 + base_wheel_gap2base) }" rpy="0 0 0"/>
      <parent link="left_motor"/>
      <child link="left_wheel"/>
      <axis xyz="0 0 1"/>
    </joint>

    <!-- ############################ -->
    <!-- ########## LINKS ########### -->
    <!-- ############################ -->

    <!-- ########## BASE ########## -->

    <!-- link: base -->
    <link name="${name}">
      <!-- plat -->
      <collision>
        <origin xyz="-0.13 0.083 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="file://$(find robot_description)/config/meshes/base.dae" scale="${robot_scale} ${robot_scale} ${robot_scale}"/>
        </geometry>
      </collision>
      <visual>
        <origin xyz="-0.13 0.083 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="file://$(find robot_description)/config/meshes/base.dae" scale="${robot_scale} ${robot_scale} ${robot_scale}"/>
        </geometry>
      </visual>
      <!-- power_source -->
      <xacro:create_box m="2" x="0.1" y="0.2" z="0.05">
        <origin xyz="0 0 0.05" rpy="0 0 0"/>
      </xacro:create_box>

    </link>


    <!-- ########## MOTORS ########## -->

    <!-- link: right_motor -->
    <link name="right_motor">
      <xacro:create_cylinder m="${base_motor_mass}" r="${base_motor_diameter/2}" l="${base_motor_lenght}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:create_cylinder>
    </link>

    <!-- link: left_motor -->
    <link name="left_motor">
      <xacro:create_cylinder m="${base_motor_mass}" r="${base_motor_diameter/2}" l="${base_motor_lenght}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:create_cylinder>
    </link>

    <!-- ########## WHEELS ########## -->

    <!-- link: right_wheel -->
    <link name="right_wheel">
      <xacro:create_cylinder m="${base_wheel_mass}" r="${base_wheel_diameter/2}" l="${base_wheel_lenght}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:create_cylinder>
      <visual>
        <origin xyz="0 0 0" rpy="0 ${-PI/2} 0" />
        <geometry>
          <mesh filename="file://$(find robot_description)/config/meshes/wheel.dae" scale="${robot_scale} ${robot_scale} ${robot_scale}"/>
        </geometry>
      </visual>
    </link>

    <!-- link: left_wheel -->
    <link name="left_wheel">
      <xacro:create_cylinder m="${base_wheel_mass}" r="${base_wheel_diameter/2}" l="${base_wheel_lenght}">
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </xacro:create_cylinder>
      <visual>
        <origin xyz="0 0 0" rpy="0 ${PI/2} 0" />
        <geometry>
          <mesh filename="file://$(find robot_description)/config/meshes/wheel.dae" scale="${robot_scale} ${robot_scale} ${robot_scale}"/>
        </geometry>
      </visual>
    </link>

    <!-- ############################ -->
    <!-- ######### PLUGINS ########## -->
    <!-- ############################ -->

    <xacro:gazebo_base reference="${name}" robotBaseFrame="${parent}" rightJoint="right_motor_to_right_wheel" leftJoint="left_motor_to_left_wheel"/>

  </xacro:macro>


  <xacro:macro name="gazebo_base" params="reference robotBaseFrame rightJoint leftJoint">
    <gazebo>
       <plugin name='${reference}_controller' filename='libgazebo_ros_diff_drive.so'>

        <ros>
          <namespace></namespace>
          <remapping>cmd_vel:=cmd_vel</remapping>
          <remapping>odom:=odom</remapping>
        </ros>

        <update_rate>30</update_rate>
        <command_topic>cmd_vel</command_topic>

        <robot_base_frame>${robotBaseFrame}</robot_base_frame>
        <left_joint>${leftJoint}</left_joint>
        <right_joint>${rightJoint}</right_joint>

        <wheel_separation>${base_wheel_diameter}</wheel_separation>
        <wheel_diameter>${base_wheel_diameter}</wheel_diameter>
        <wheel_torque>${base_wheel_wheel_torque}</wheel_torque>

        <max_wheel_torque>20</max_wheel_torque>
        <max_wheel_acceleration>1.0</max_wheel_acceleration>

        <publish_odom>true</publish_odom>
        <publish_odom_tf>true</publish_odom_tf>
        <publish_wheel_tf>true</publish_wheel_tf>

        <odometry_topic>odom</odometry_topic>
        <odometry_frame>odom</odometry_frame>
        <odometryRate>100.0</odometryRate>

      </plugin>


    </gazebo>
  </xacro:macro>


</robot>
