version: '2'

services:

  micro-ros-agent:
    container_name: microros
    image: microros/micro-ros-agent:humble
    command: ["serial", "--dev", "/dev/ttyACM0", "-v6"]
    volumes:
      - /dev:/dev
    privileged: true
    network_mode: host
    tty: true
    stdin_open: true

  setup:
    image: navtech:latest
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - micro-ros-agent
    volumes_from:
      - micro-ros-agent
    volumes:
      - ${PWD}/src:/ws_navtech/src:rw
    security_opt:
      - seccomp:unconfined
    ipc: host
    privileged: true
    stdin_open: true
    tty: true 
    command:
      - /bin/bash
      - -c
      - |
        ls 