<?xml version="1.0"?>
<robot name="robot"
  xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:include filename="$(find robot_description)/config/urdf/macros/parts/base_robot.urdf.xacro" />
  <xacro:include filename="$(find robot_description)/config/urdf/macros/parts/rplidar_s2.urdf.xacro"/>

  <!-- link: base_footprint -->
  <link name='base_footprint'/>
  
  <!-- ##### -->
  <!-- Robot -->
  <!-- ##### -->

  <!-- Base -->
  <xacro:base name="base_link" parent="base_footprint">
      <origin xyz="0 0 ${base_wheel_diameter/4}" rpy="0 0 0"/>
  </xacro:base>

  <!-- base laser front -->
  <xacro:rplidar_a1m6 name="base_scan_front" parent="base_link">
    <origin xyz="0.27 ${0} ${rplidar_s2_size_z/2}" rpy="0 0 0"/>
  </xacro:rplidar_a1m6>


</robot>
