/**:
  ros__parameters:
    # Parâmetros geométricos do robô:
    # Diâmetro da roda omnidirecional padrão
    wheelDiameter: 0.1
    # Comprimento do robô de centro de roda a centro de roda
    robotLength: 0.5
    # Largura de centro de roda a centro de roda
    robotWidth: 0.548
    # Desvio padrão da velocidade em x
    devX: 0.447
    # Desvio padrão da velocidade em y
    devY: 0.447
    # Desvio padrão da velocidade em z
    devZ: 0.447
    # Desvio padrão da velocidade de rotação em roll
    devRoll: 0.447
    # Desvio padrão da velocidade de rotação em pitch
    devPitch: 0.447
    # Desvio padrão da velocidade de rotação em yaw
    devYaw: 0.447
    # Enviar transformação TF
    sendTransform: true