name: CI
orbs:
  codecov: codecov/codecov@3
on: [push, pull_request]
jobs:
  build:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt