name: environment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  
jobs:
  Checkout:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init --recursive
      
  Build:
    needs: [Checkout]
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker image
        run: docker build -t navtech:latest .
        working-directory: ${{ github.workspace }}

  Library:
    needs: [Build]
    runs-on: ubuntu-latest
    env:
      working-directory: ./
    steps:
      - name: Running the tests
        run: docker run navtech:latest bash -c "ros2 run robot library.py"
        working-directory: ${{env.working-directory}}