name: environment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  
jobs:
  Checkout:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init --recursive