name: environment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  
jobs:
  Checkout:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init --recursive
      
  Build:
    needs: [Checkout]
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .  # O diretório atual é usado como contexto para a construção da imagem
          push: true  # Para fazer o push da imagem para um registro, se necessário
          tags: navtech:latest  # Tags da imagem Docker

  Library:
    needs: [Build]
    runs-on: ubuntu-latest
    env:
      working-directory: ./
    steps:
      - name: Running the tests
        run: docker run navtech:latest bash -c "ros2 run robot library.py"
        working-directory: ${{env.working-directory}}