name: environment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  
jobs:
  Checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Checkout submodules
        run: git submodule update --init --recursive
      
  Build:
    needs: [Checkout]
    runs-on: ubuntu-latest
    env:
      working-directory: ./
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag navtech:latest